# Generated by Django 5.0.4 on 2026-03-02 00:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('total_capacity', models.PositiveIntegerField()),
                ('available_spots', models.PositiveIntegerField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SATImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_url', models.URLField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_imported', models.IntegerField(default=0)),
                ('execution_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'sat_import_batches',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(max_length=254)),
                ('ticket_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.event')),
            ],
            options={
                'db_table': 'reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanceledTaxpayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('person_type', models.CharField(blank=True, default='', max_length=50)),
                ('assumption', models.CharField(blank=True, default='', max_length=300)),
                ('credit_number', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canceled_taxpayers', to='api.satimportbatch')),
            ],
            options={
                'db_table': 'sat_canceled_taxpayers',
                'indexes': [models.Index(fields=['rfc'], name='idx_canceled_rfc'), models.Index(fields=['batch'], name='idx_canceled_batch')],
            },
        ),
    ]
