# Generated by Django 5.0.4 on 2026-03-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceledtaxpayer',
            name='person_type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
